language: haskell

ghc:
  # Older than GHC 7.8 aren't supported by the package.
  - 7.8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgtk2.0-dev libwxgtk3.0-dev libwxgtk-media3.0-dev

install:
  # gtk2hs-buildtools-0.13.0.3 depends on alex >= 3.0.1, happy >= 1.18.9,
  # therefore it is necessary to get newer versions then default.
  - cabal install alex happy
  - cabal install gtk2hs-buildtools alex happy
  - cabal install --only-dependencies

script:
  # Option -fpedantic turns on additional wornings in addition to -Wall.
  - cabal configure -fpedantic && cabal build

  # Following line tests if sdist package is created correctly.
  - cabal sdist && cabal install dist/toolbox-*.tar.gz
